<?php

return [
    'layout_statuses' => [
        'draft',
        'published',
        'archived',
    ],

    'component_types' => [
        'learning_panel',
        'cms_panel',
        'hotspot_marker',
        'checklist_panel',
        'status_board',
        'wall_sign',
        'floor_arrow',
        'pressure_gauge',
        'hvac_diffuser',
        'return_grille',
        'equipment_island',
        'cleanroom_door',
        'cleaning_station',
        'waste_bin',
        'qa_qc_checkpoint',
        'mini_review_panel',
        'reflection_panel',
        'completion_panel',
    ],

    'default_room_bounds' => [
        'x' => [-4, 4],
        'z' => [-4, 4],
    ],

    'position_presets' => [
        'north_wall_center' => [
            'label' => 'North Wall Center',
            'position' => [0, 1.7, -3.8],
            'rotation' => [0, 0, 0],
            'scale' => [1, 1, 1],
        ],
        'north_wall_left' => [
            'label' => 'North Wall Left',
            'position' => [-2.4, 1.7, -3.8],
            'rotation' => [0, 0, 0],
            'scale' => [1, 1, 1],
        ],
        'north_wall_right' => [
            'label' => 'North Wall Right',
            'position' => [2.4, 1.7, -3.8],
            'rotation' => [0, 0, 0],
            'scale' => [1, 1, 1],
        ],
        'south_wall_center' => [
            'label' => 'South Wall Center',
            'position' => [0, 1.7, 3.8],
            'rotation' => [0, 3.1416, 0],
            'scale' => [1, 1, 1],
        ],
        'east_wall_center' => [
            'label' => 'East Wall Center',
            'position' => [3.8, 1.7, 0],
            'rotation' => [0, -1.5708, 0],
            'scale' => [1, 1, 1],
        ],
        'west_wall_center' => [
            'label' => 'West Wall Center',
            'position' => [-3.8, 1.7, 0],
            'rotation' => [0, 1.5708, 0],
            'scale' => [1, 1, 1],
        ],
        'entry_left' => [
            'label' => 'Entry Left',
            'position' => [-1.6, 1.45, 3.55],
            'rotation' => [0, 3.1416, 0],
            'scale' => [0.9, 0.9, 0.9],
        ],
        'entry_right' => [
            'label' => 'Entry Right',
            'position' => [1.6, 1.45, 3.55],
            'rotation' => [0, 3.1416, 0],
            'scale' => [0.9, 0.9, 0.9],
        ],
        'equipment_island_front' => [
            'label' => 'Equipment Island Front',
            'position' => [0, 1.35, 0.85],
            'rotation' => [0, 3.1416, 0],
            'scale' => [0.9, 0.9, 0.9],
        ],
        'equipment_island_right' => [
            'label' => 'Equipment Island Right',
            'position' => [1.65, 1.35, -0.45],
            'rotation' => [0, -1.5708, 0],
            'scale' => [0.9, 0.9, 0.9],
        ],
        'floor_center' => [
            'label' => 'Floor Center',
            'position' => [0, 0.08, 0],
            'rotation' => [-1.5708, 0, 0],
            'scale' => [1, 1, 1],
        ],
        'ceiling_center' => [
            'label' => 'Ceiling Center',
            'position' => [0, 3.65, 0],
            'rotation' => [1.5708, 0, 0],
            'scale' => [1, 1, 1],
        ],
    ],

    'component_defaults' => [
        'learning_panel' => [
            'id' => 'learning-panel-draft',
            'type' => 'learning_panel',
            'title' => 'Tujuan Pembelajaran',
            'body' => 'Jelaskan tujuan belajar singkat untuk komponen ini.',
            'variant' => 'primary',
            'active' => true,
            'transform' => [
                'position' => [0, 1.7, -3.8],
                'rotation' => [0, 0, 0],
                'scale' => [1, 1, 1],
            ],
        ],
        'cms_panel' => [
            'id' => 'cms-panel-draft',
            'type' => 'cms_panel',
            'title' => 'Konten CMS',
            'body' => 'Panel ini mengambil konten dari CMS sesuai contentKey.',
            'variant' => 'content',
            'active' => true,
            'contentKey' => 'cpob_12_aspects',
            'transform' => [
                'position' => [0, 1.7, -3.8],
                'rotation' => [0, 0, 0],
                'scale' => [1, 1, 1],
            ],
        ],
        'hotspot_marker' => [
            'id' => 'hotspot-draft',
            'type' => 'hotspot_marker',
            'title' => 'Titik Inspeksi',
            'body' => 'Amati elemen ruang bersih ini dan hubungkan dengan prinsip CPOB.',
            'variant' => 'cyan',
            'active' => true,
            'transform' => [
                'position' => [0, 1.7, -3.8],
                'rotation' => [0, 0, 0],
                'scale' => [1, 1, 1],
            ],
            'interaction' => [
                'eventName' => 'gmp_standard_room.hotspot_inspected',
                'evidenceEventType' => 'hotspot_inspected',
                'requiredForCompletion' => true,
            ],
        ],
        'checklist_panel' => [
            'id' => 'checklist-panel-draft',
            'type' => 'checklist_panel',
            'title' => 'Cek Kesiapan CPOB',
            'body' => 'Gunakan panel ini untuk memandu pemeriksaan kesiapan ruang.',
            'variant' => 'checklist',
            'active' => true,
            'transform' => [
                'position' => [0, 1.35, 0.85],
                'rotation' => [0, 3.1416, 0],
                'scale' => [0.9, 0.9, 0.9],
            ],
        ],
        'status_board' => [
            'id' => 'status-board-draft',
            'type' => 'status_board',
            'title' => 'Status Ruang',
            'body' => 'Tampilkan status kebersihan, tekanan, atau kesiapan operasional.',
            'variant' => 'green',
            'active' => true,
            'transform' => [
                'position' => [-3.8, 1.7, 0],
                'rotation' => [0, 1.5708, 0],
                'scale' => [1, 1, 1],
            ],
        ],
        'wall_sign' => [
            'id' => 'wall-sign-draft',
            'type' => 'wall_sign',
            'title' => 'Ruang Standar CPOB',
            'body' => 'Label area produksi terkendali.',
            'variant' => 'standard',
            'active' => true,
            'transform' => [
                'position' => [0, 1.7, -3.8],
                'rotation' => [0, 0, 0],
                'scale' => [1, 1, 1],
            ],
        ],
        'floor_arrow' => [
            'id' => 'floor-arrow-draft',
            'type' => 'floor_arrow',
            'title' => 'Alur Personel',
            'body' => 'Gunakan panah lantai untuk menunjukkan arah alur kerja.',
            'variant' => 'cyan',
            'active' => true,
            'transform' => [
                'position' => [0, 0.08, 0],
                'rotation' => [-1.5708, 0, 0],
                'scale' => [1, 1, 1],
            ],
        ],
    ],
];
